
# path to assemblies
assemblies: /home/malcummi/Data/Manuscripts/Femoral_Head_2019/output/assemblies/final_assemblies

#path for output
output : /home/malcummi/Data/Manuscripts/Femoral_Head_2019/output/phylosift

#path to phylosift
phylosift: /home/malcummi/Data/PhyloSift
