###Configuration for pangenomelord

# path to reads
assembly_path: /home/mlcummin/Data/Manuscripts/Kira_ColV/fastas_new
#path to output directory:
output: /home/mlcummin/Data/Manuscripts/Kira_ColV/output/pangenome_new
